# Generated by Django 2.0.13 on 2019-06-25 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cofre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('nome', models.CharField(max_length=50)),
                ('saldo', models.IntegerField()),
                ('local', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.IntegerField()),
                ('cofre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cofre')),
            ],
        ),
    ]
