# Generated by Django 2.0.13 on 2019-06-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190625_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofre',
            name='id',
        ),
        migrations.AlterField(
            model_name='cofre',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo do Cofre.', max_digits=10, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='cofre',
            name='token',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor da Transação.', max_digits=10, verbose_name='Valor'),
        ),
    ]
