# Generated by Django 2.0.13 on 2019-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190625_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
